<?php

/**
 *  Implements hook_ 
 */
/**
 * Implements of hook_services_resources().
 */
function custom_change_password_services_resources() {
  $api = array(
    'change_password_by_token' => array(
      'operations' => array(
        'retrieve' => array(
          'help' => 'Obtener la fecha de aplicacion a un puesto',
          'callback' => '_custom_change_password_change_password',
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'u_email',
              'type' => 'string',
              'description' => 'Correo del usuario a modificar',
              'source' => array('param' => 'u_email'),
              'optional' => TRUE,
              'default' => '0',
            ),
            array(
              'name' => 'token',
              'type' => 'string',
              'description' => 'token',
              'source' => array('param' => 'token'),
              'optional' => TRUE,
              'default' => '0',
            ),
          ),
        ),
      ),
    ),
  );
  return $api;
}

function _custom_change_password_change_password($u_email, $token) {
  // Check for mad values
  return cambio_password($u_email, $token);
}

/**
 * Obtener fecha de aplicacion
 */
function cambio_password($u_email, $token) {
  // cambio de contraseña  
  return array('email' => $u_email, 'token' => $token);
}